config/routes.rb
Library::Application.routes.draw do

#  get "static/index"

  root :to => 'static#index'

  get 'user/return/:isbn' => 'return#create', as: 'return_book'
  post '/return' => 'return#create'

  get '/books/new' => 'books#new', as: 'new_book'

  get '/books/preview' => 'books#preview', as: 'book_preview'
  post '/books/preview' => 'books#preview'

  post '/books' => 'books#create', as: 'book_create'

  get '/books/:isbn' => 'books#show', as: 'book'

  get '/mybooks' => 'books#mybooks', as: 'mybooks'

  get '/books/:isbn/edit' => 'books#edit', as: 'edit_book'

  put '/books/:isbn' => 'books#update'

  get 'book/:isbn/check_out' => 'checkouts#create', as: 'check_out'
  post '/checkouts' => 'checkouts#create'

  get '/checkouts' => 'checkouts#index'

  match '/auth/:provider/callback' => 'sessions#create'
  match '/auth/failure' => 'sessions#failure'

  match '/signout' => 'sessions#destroy', :as => :signout
  match '/signin' => 'sessions#new', :as => :signin
  match '/signin/8thlight' => 'sessions#open_id', :as => :signin_openid

  get 'book/:isbn/waiting_list' => 'waitinglists#create', as: 'wait_list'
  post '/waitinglist' => 'waitinglists#create'

  post '/search' => 'books#search'
end

app/models/book.rb
class Book < ActiveRecord::Base
  include ApplicationDecorator
  has_many :checkouts
  has_many :waitinglist
  has_many :users, :through => :checkouts
  has_many :users, :through => :waitinglist

  attr_accessible :isbn, :quantity, :quantity_left

  validates :isbn, :length => {
    :maximum => 17,
    :minimum => 10
  }

  validate :validate_isbn
  validates :isbn, :uniqueness => true
  validates :quantity, :presence => true, :numericality => { :greater_than_or_equal_to => 0 }

  API_KEY = "AIzaSyAqerTH3Ee8TcKFLn695LAu8HQm9SBFrn0"

  def get_attr(attr)
    BookDecorator.get_book_attr(isbn, attr)
  end

  def api_book
    @api_book ||= BookDecorator.get_google_book(isbn)
  end

  def validate_isbn
    if api_book.empty?
       errors.add(:isbn, 'does not exist')
       return false
    else
      return true
    end
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
    @book = Book.new
  end

  def preview
    @book = Book.new(params[:book])
  end

  def create
    @book = Book.new(params[:book])
    @book.quantity_left = @book.quantity
    if @book.save
      flash[:success] = "The book was saved successfully"
      redirect_to root_path
    else
      flash[:error] = "Please fill in the fields correctly"
      render :action => "new"
    end
  end

  def mybooks
    @checkouts = Checkout.where(user_id:session[:user_id])
  end

  def show
    @book = Book.find_by_isbn(params[:isbn])
    @checked_out_books = Checkout.where(book_id: @book.id)
    @waiting_list = Waitinglist.where(book_id: @book.id)
  end

  def edit
    @book = Book.find_by_isbn(params[:isbn])
  end

  def update
    @book = Book.find_by_isbn(params[:isbn])
    @book.quantity_left += ((params[:book][:quantity].to_i) - @book.quantity)
    @book.update_attributes(params[:book])
    redirect_to :action => "show"
  end

  def search
    query = {:isbn  =>  params[:search_book]}
    @results = Book.where(query)
  end
end

app/views/books/check_out.html.erb
<h3>Check out</h3>
<% if flash[:notice] %>
  <%= flash[:notice] %>
<% end %>

app/views/books/edit.html.erb
<h1>Edit Book Quantity</h1>

<%= form_for @book, :url => book_path(@book.isbn) do |f| %>

      <img src="<%= @book.get_attr("image") %>">

      <div><%= @book.get_attr("title") %></div>

      <div><%= @book.get_attr("author") %></div>

      <div><%= @book.isbn %></div>

      <div><%= @book.quantity_left %></div>

      <div><%= f.label "Quantity" %></div>

      <div><%= f.number_field "quantity", min: 0%></div>

      <input type="submit" class="btn btn-primary" id="submit_button">
  <% end %>

app/views/books/index.html.erb
<h1>List of Books</h1>

app/views/books/mybooks.html.erb
<h2>My books</h2>
<ul>
  <% @checkouts.each do |checkout|%>
    <li><%= checkout.book.get_attr("title") %> </li>
  <% end %>
</ul>

app/views/books/new.html.erb
  <h3>Register Book</h3>

  <%= form_for @book, :url => book_preview_path do |f| %>

      <%= render 'shared/error_messages' %>

      <div><%= f.text_field :isbn, placeholder: "ISBN" %></div>

      <div><%= f.number_field :quantity, placeholder: "Quantity", min: 0%></div>

      <div><%= f.submit "Preview Book", class: "btn btn-primary" %></div>

    <% end %>

app/views/books/preview.html.erb
<h3>Book Preview</h3>

<%= render 'shared/error_messages' %>

<% if @book.valid? %>
  <img src="<%= @book.get_attr("image") %>">
  <p>Title: <%= @book.get_attr("title") %></p>
  <p>Author: <%= @book.get_attr("author") %></p>

  <%= form_for @book, :url => book_create_path do |f| %>


    <div><%= f.text_field :isbn, :value => @book.isbn %></div>

    <div><%= f.number_field :quantity, :value => @book.quantity %></div>

    <div><%= f.submit "Add Book", class: "btn btn-primary", id: "submit_button" %></div>

  <% end %>
<% end %>

  <%= render 'shared/error_messages' %>

<%= link_to "Try again", new_book_path %>

app/views/books/search.html.erb
<h1> Search Result </h1>

<table id="book-table" class="table table-bordered table-hover">
  <thead>
    <tr>
      <th>Cover</th>
      <th>Title</th>
      <th>Author</th>
      <th>ISBN</th>
      <th>Quantity</th>
      <th>Quantity Left</th>
    </tr>
  </thead>
  <tbody>
    <% @results.each do |book| %>
    <tr>
      <td><img src="<%= book.get_attr("image") %>"></td>
      <td><%= link_to book.get_attr("title"), book_path(book.isbn) %></td>
      <td><%= book.get_attr("author") %></td>
      <td><%= book.isbn %></td>
      <td><%= book.quantity %></td>
      <td><%= book.quantity_left %></td>
    </tr>
  <% end %>
  <tbody>
</table>

app/views/books/show.html.erb
<p>Image:</p>
<img src="<%= @book.get_attr("image") %>">
<p>Title: <%= @book.get_attr("title") %></p>
<p>Author: <%= @book.get_attr("author") %></p>
<p>isbn: <%= @book.isbn %></p>
<p>quantity: <%= @book.quantity %></p>
<p>Quantity Left: <%= @book.quantity_left %></p>

<% if user_signed_in? %>
<p>Currently borrowing users</p>
<ul>
  <% @checked_out_books.each do |book| %>
    <li><%= book.user.name %> at <%= book.check_out_date %></li>
  <% end %>
</ul>
<p>Waiting list</p>
<ul>
  <% @waiting_list.each do |list| %>
    <li><%= list.user.name %></li>
  <% end %>
</ul>

  <% if user_signed_in? && book_not_checked_out?(@book) %>
    <%= link_to "Check out", check_out_path(@book.isbn) %></br>
  <% end %>

  <% if not_on_waiting_list?(@book) && @book.quantity_left == 0 %>
    <%= link_to "add myself to the waiting list", wait_list_path(@book.isbn) %>
  <% end %>

  <% if user_checked_out_book?(@book) %>
    <%= link_to "return", return_book_path(@book.isbn) %></td>
  <% end %>

<% end %>