config/routes.rb
Library::Application.routes.draw do

#  get "static/index"

  root :to => 'static#index'

  get 'user/return/:isbn' => 'return#create', as: 'return_book'
  post '/return' => 'return#create'

  get '/books/new' => 'books#new', as: 'new_book'

  get '/books/preview' => 'books#preview', as: 'book_preview'
  post '/books/preview' => 'books#preview'

  post '/books' => 'books#create', as: 'book_create'

  get '/books/:isbn' => 'books#show', as: 'book'

  get '/mybooks' => 'books#mybooks', as: 'mybooks'

  get '/books/:isbn/edit' => 'books#edit', as: 'edit_book'

  put '/books/:isbn' => 'books#update'

  get 'book/:isbn/check_out' => 'checkouts#create', as: 'check_out'
  post '/checkouts' => 'checkouts#create'

  get '/checkouts' => 'checkouts#index'

  match '/auth/:provider/callback' => 'sessions#create'
  match '/auth/failure' => 'sessions#failure'

  match '/signout' => 'sessions#destroy', :as => :signout
  match '/signin' => 'sessions#new', :as => :signin
  match '/signin/8thlight' => 'sessions#open_id', :as => :signin_openid

  get 'book/:isbn/waiting_list' => 'waitinglists#create', as: 'wait_list'
  post '/waitinglist' => 'waitinglists#create'

  post '/search' => 'books#search'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Kihon</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="navbar">
    <div class="navbar-inner">
      <ul class="nav">
        <li class="brand"><%= link_to "Kihon", root_path %></li>
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Add Book", new_book_path  %></li>
        <% if user_signed_in? %>
          <li><%= link_to "View Your Books", mybooks_path %></li>
          <li>Signed in as <%= current_user.email %>. </li>
          <li><%= link_to "Not you? Sign out", signout_path, :method => :delete %></li>
          <%= form_tag('/search', method: 'post') do %>
            <%= label_tag(:search_book, 'search: ') %>
            <%= text_field_tag(:search_book) %>
            <%= submit_tag('search') %>
          <% end %>
        <% else %>
        <li><%= link_to "sign in with Google", signin_path %></li>
        <li><%= link_to "sign in with your 8th Light account", signin_openid_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
  <div class="container">
    <%= yield %>
  </div>

</body>
</html>